config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :departments
  
  get 'startup' => 'orders#startup'
  get 'highsalary' => 'orders#highsalary'
  get 'order_by_age_asc' => 'orders#order_by_age_asc'
  get 'order_by_age_desc' => 'orders#order_by_age_desc'
  get 'order_by_dept' => 'orders#order_by_dept'
  get 'order_by_salary_asc' => 'orders#order_by_salary_asc'
  get 'order_by_salary_desc' => 'orders#order_by_salary_desc'
  get 'retired_list' => 'orders#retired_list'
  get 'top5emp' => 'orders#top5emp'
  get 'top5sremp_by_age' => 'orders#top5sremp_by_age'
  get 'lowsalaryandsenior' => 'orders#lowsalaryandsenior'
  
  

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:dept_name, :description)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
	
	#----> C
	#@employees = Employee.order(:age)
	#@employees = Employee.order(age: :desc)
	
	#---->D
	#@employees = Employee.order(:department_id)
	
	#---->E
	#@employees = Employee.order(:salary)
	#@employees = Employee.order(salary: :desc)
	
	#---->F
	#@employees = Employee.where("age > ?", 65)

	#---->G
	#@employees = Employee.order(salary: :desc).limit(1)
	
	#---->H
	#@employees = Employee.order(salary: :desc).limit(5)
	
	#---->I----?
	##############################@employees = Employee.order('salary DESC, department_id')#.offset(2)
	
	#---->J
	#@employees = Employee.order(age: :desc).limit(5)
	
	#---->K----?
	#@employees = Employee.last(salary: :desc)
	#p @employees.first
	#p @employees.last
	
	#---->L
	#@employees = Employee.order(:salary, age: :desc).limit(1)
	
  end
  
  
  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :email, :age, :salary, :department_id)
    end
end

app/controllers/orders_controller.rb

class OrdersController < ApplicationController
  
  def highsalary
    @employees = Employee.order(salary: :desc).limit(1)
  end
  
  def order_by_age_asc
	@employees = Employee.order(:age)
  end
  
  def order_by_age_desc
	@employees = Employee.order(age: :desc)
  end

  def order_by_dept
    @employees = Employee.order(:department_id)
  end
  
  def order_by_salary_asc
    @employees = Employee.order(:salary)
  end
  
  def order_by_salary_desc
	@employees = Employee.order(salary: :desc)
  end
  
  def retired_list
	@employees = Employee.where("age > ?", 65)
  end
  
  def top5emp
	@employees = Employee.order(salary: :desc).limit(5)
  end
  
  def top5sremp_by_age
	@employees = Employee.order(age: :desc).limit(5)
  end
  
  def lowsalaryandsenior
	@employees = Employee.order(:salary, age: :desc).limit(1)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dept_name %><br>
    <%= f.text_field :dept_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Departments</h1>

<table>
  <thead>
    <tr>
      <th>Dept name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.dept_name %></td>
        <td><%= department.description %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dept name:</strong>
  <%= @department.dept_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @department.description %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.number_field :salary %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br>
    <%= f.text_field :department_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border: 3px solid black;
  }
  th{
    border: 1px solid blue;
  }
   td {
    border: 1px solid orange;
  }
</style>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.department.dept_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @employee.age %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @employee.salary %>
</p>

<p>
  <strong>Department:</strong>
  <%= @employee.department %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DepEmp</title>
  <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'default', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/highsalary.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border: 3px solid black;
  }
  th{
    border: 1px solid blue;
  }
   td {
    border: 1px solid orange;
  }
</style>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.department.dept_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/lowsalaryandsenior.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border: 3px solid black;
  }
  th{
    border: 1px solid blue;
  }
   td {
    border: 1px solid orange;
  }
</style>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.department.dept_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/order_by_age_asc.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border: 3px solid black;
  }
  th{
    border: 1px solid blue;
  }
   td {
    border: 1px solid orange;
  }
</style>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.department.dept_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/order_by_age_desc.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border: 3px solid black;
  }
  th{
    border: 1px solid blue;
  }
   td {
    border: 1px solid orange;
  }
</style>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.department.dept_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/order_by_dept.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border: 3px solid black;
  }
  th{
    border: 1px solid blue;
  }
   td {
    border: 1px solid orange;
  }
</style>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.department.dept_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/order_by_salary_asc.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border: 3px solid black;
  }
  th{
    border: 1px solid blue;
  }
   td {
    border: 1px solid orange;
  }
</style>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.department.dept_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/order_by_salary_desc.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border: 3px solid black;
  }
  th{
    border: 1px solid blue;
  }
   td {
    border: 1px solid orange;
  }
</style>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.department.dept_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/retired_list.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border: 3px solid black;
  }
  th{
    border: 1px solid blue;
  }
   td {
    border: 1px solid orange;
  }
</style>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.department.dept_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/startup.html.erb
 <! doctype html>
 <html>
 <head>
 <title> My App </title>
 </head>
 <body>
 <h1>My App</h1>
	<ul>
		<li> <a href="http://localhost:3000/employees"; target="_blank">list of all the employees.</a></li>
			<br>
			<br>
		<li><a href="http://localhost:3000/order_by_age_asc"; target="_blank">All employees order by age. Ascending </a></li>
			<br>
			<a href="http://localhost:3000/order_by_age_desc"; target="_blank">All employees order by age. Descending </a>
			<br>
			<br>
		<li><a href="http://localhost:3000/order_by_dept"; target="_blank">All employees order by department.</a></li>
			<br>
			<br>
		<li><a href="http://localhost:3000/order_by_salary_asc"; target="_blank">All employees order by salary. Ascending</a></li>
			<br>
			<a href="http://localhost:3000/order_by_salary_desc"; target="_blank">All employees order by salary. descending</a>
			<br>
			<br>
		<li><a href="http://localhost:3000/retired_list"; target="_blank">All employees who retired from your company(retd age 65).</a></li>
			<br>
			<br>
		<li><a href="http://localhost:3000/highsalary"; target="_blank">The employee with highest salary.</a></li>
			<br>
			<br>
		<li><a href="http://localhost:3000/top5emp"; target="_blank">Top 5 employees based on salary.</a></li>
			<br>
			<br>
		<li>Top salaried employee by department.</li>
			 &nbsp &nbsp &nbsp &nbsp &nbspSORRY, I'M UNABLE TO DO IT
			<br>
			<br>
		<li><a href="http://localhost:3000/top5sremp_by_age"; target="_blank">Top 5 senior most employees by age.</a></li>
			<br>
			<br>
		<li>The employees with highest and lowest salary.</li>
			&nbsp &nbsp &nbsp &nbsp &nbspSORRY, I'M UNABLE TO DO IT
			<br>
			<br>
		<li><a href="http://localhost:3000/lowsalaryandsenior"; target="_blank">The employee with lowest salary but senior most in the company.</a></li>
			<br>
	</ul>
	  
</body>	  
</html>

app/views/orders/top5emp.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border: 3px solid black;
  }
  th{
    border: 1px solid blue;
  }
   td {
    border: 1px solid orange;
  }
</style>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.department.dept_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/orders/top5sremp_by_age.html.erb
<p id="notice"><%= notice %></p>

<style>
  table {
    border: 3px solid black;
  }
  th{
    border: 1px solid blue;
  }
   td {
    border: 1px solid orange;
  }
</style>

<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.department.dept_name %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>